var D=[
["Solid-State Battery Pack","Today's liquid-electrolyte batteries can overheat, and range drops when petrol-free travel is the only option.","Replace the pack with solid-state cells: higher energy density, faster charging and far lower fire risk.",["Longer range for 8 passengers plus luggage","Safer in crashes and heat","Longer battery life"]],
["Solar Roof Skin","A large van roof is wasted space, and charging points may be scarce or unreliable.","Thin solar panels over the roof and body add free daily range and power cabin systems if the grid fails.",["Extra daily kilometres from sunlight","Keeps AC, lights and safety systems alive","Ideal for sunny regions like India"]],
["Vehicle-to-Home / Grid (V2X)","Blackouts and fuel crises leave homes, clinics and shelters without power.","Bi-directional charging turns the vehicle into a mobile power bank that can feed a home or support the grid.",["Emergency backup power","Earns value by supporting the grid","Community resilience in disasters"]],
["Swappable Battery Modules","Long charging waits and too few stations will slow down a shared, high-use vehicle.","Standard modular packs that can be swapped in minutes at a service point.",["Near-zero downtime for fleets","Easy upgrades as batteries improve","Lower repair and replacement costs"]],
["Ultra-Fast 800V Charging","Slow charging makes EVs impractical for long family trips and taxi use.","An 800V architecture with smart and wireless charging support for very quick top-ups.",["Short stops on long journeys","Less stress on the power grid via smart scheduling","Convenient hands-free charging at home"]],
["AI Safety Shield","Crowded future roads raise collision risk, especially with 6-8 people on board.","LiDAR, radar and camera fusion with driver-alert AI and vehicle-to-vehicle (V2V) communication.",["Automatic emergency braking","Fatigue and distraction warnings","Anticipates hazards before the driver can"]],
["Battery Fire & Flood Guard","Extreme weather, floods and battery fires are growing risks.","A sealed, waterproof pack with thermal-runaway containment, underbody armour and early-warning sensors.",["Safe passage through flooded roads","Fire isolated before it spreads","Automatic alerts and passenger evacuation guidance"]],
["Circular, Recyclable Build","EV production and old batteries can create a new waste problem.","Lightweight recycled materials, easy-to-dismantle design and second-life reuse of batteries for energy storage.",["Lower carbon footprint","Less raw-material dependence","A sustainable future for the planet"]]];
var g=document.getElementById("grid"),ov=document.getElementById("ov"),mod=document.getElementById("mod"),cur=0;
D.forEach(function(d,i){var b=document.createElement("button");b.className="card";b.innerHTML="<i>0"+(i+1)+"</i><h3>"+d[0]+"</h3><p>"+d[1].split(".")[0].slice(0,0)+d[2].split(":")[0].split(".")[0]+".</p><span class='more'>Open idea &rarr;</span>";b.onclick=function(){show(i)};g.appendChild(b)});
function show(i){cur=(i+D.length)%D.length;var d=D[cur];
mod.innerHTML="<button class='x' aria-label='Close' onclick='hide()'>&times;</button><i style='color:var(--gold);letter-spacing:.2em;font-size:12px;font-style:normal'>UPGRADE 0"+(cur+1)+" / 08</i><h3>"+d[0]+"</h3><h4>The Future Problem</h4><p>"+d[1]+"</p><h4>Proposed Upgrade</h4><p>"+d[2]+"</p><h4>Benefits</h4><ul>"+d[3].map(function(x){return"<li>"+x+"</li>"}).join("")+"</ul><div class='nv'><button onclick='show(cur-1)'>&larr; Prev</button><button onclick='show(cur+1)'>Next &rarr;</button></div>";
ov.classList.add("on");mod.scrollTop=0}
function hide(){ov.classList.remove("on")}
ov.addEventListener("click",function(e){if(e.target===ov)hide()});
document.addEventListener("keydown",function(e){if(!ov.classList.contains("on"))return;if(e.key==="Escape")hide();if(e.key==="ArrowRight")show(cur+1);if(e.key==="ArrowLeft")show(cur-1)});
